services:
  # Databases
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    privileged: true
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: ['redis-server', '--appendonly', 'yes']
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      - postgres
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      # target: development
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
volumes:
  redis-data:
  postgres-data:
